### ISSUE TITLE
Broken build with gcc 7.2.0

### ISSUE THREAD

**Issue by malikolivier** [thedmd/imgui-node-editor#7]
Commit a65df7cd8ef625133ed3c60515561fec48858f42 explicitly drops support for 64-bit builds.
Is it just an experiment?
I am just curious to know why this choice was made.

If this is a hassle, please do not bother explaining the details, as this is your project after all.

*EDIT 2018-05-24*: This was a complete misunderstanding. 64-bit support is not dropped! See my next message for the real issue.

**Comment by thedmd** [comment]
Changes actually were made for two reasons:
* distinguish between ID types
* enable ID to be wide enough to hold 64-bit pointer

In what way this commit drops 64-bit support? Can you elaborate?

**Comment by malikolivier** [comment]
> In what way this commit drops 64-bit support? Can you elaborate?

I am very sorry. I will rename the title of the issue.
I misread your commit message.  I am completely stupid.

Let me explain my *real* problem:

Build is broken on commit a65df7c with Ubuntu 17.10 on gcc 7.2.0. Here is the error output:

```
malik@malik-XPS-13-9360:~/workspace/opensource/imgui-node-editor/Build$ make
[ 20%] Built target ImGui
Scanning dependencies of target NodeEditor
[ 25%] Building CXX object NodeEditor/CMakeFiles/NodeEditor.dir/Source/NodeEditor.cpp.o
In file included from /home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Source/NodeEditor.cpp:10:0:
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h:49:11: error: ‘template<class T, class Tag> struct ax::NodeEditor::Details::SafeType’ used without template parameters
     using SafeType::SafeType;
           ^~~~~~~~
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h: In constructor ‘ax::NodeEditor::Details::SafePointerType<Tag>::SafePointerType()’:
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h:50:24: error: class ‘ax::NodeEditor::Details::SafePointerType<Tag>’ does not have any field named ‘SafeType’
     SafePointerType(): SafeType(Invalid) {}
                        ^~~~~~~~
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h: In constructor ‘ax::NodeEditor::Details::SafePointerType<Tag>::SafePointerType(T*)’:
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h:51:68: error: class ‘ax::NodeEditor::Details::SafePointerType<Tag>’ does not have any field named ‘SafeType’
     template <typename T = void> explicit SafePointerType(T* ptr): SafeType(reinterpret_cast<uintptr_t>(ptr)) {}
                                                                    ^~~~~~~~
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h: In member function ‘T* ax::NodeEditor::Details::SafePointerType<Tag>::ToPointer() const’:
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h:52:85: error: there are no arguments to ‘Get’ that depend on a template parameter, so a declaration of ‘Get’ must be available [-fpermissive]
     template <typename T = void> T* ToPointer() const { return reinterpret_cast<T*>(Get()); }
                                                                                     ^~~
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h:52:85: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h: In instantiation of ‘const ax::NodeEditor::NodeId ax::NodeEditor::Details::SafePointerType<ax::NodeEditor::NodeId>::Invalid’:
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Source/Editor.h:78:28:   required from here
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h:61:11: error: no matching function for call to ‘ax::NodeEditor::NodeId::NodeId(<brace-enclosed initializer list>)’
 const Tag SafePointerType<Tag>::Invalid{0};
           ^~~~~~~~~~~~~~~~~~~~
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h:51:43: note: candidate: template<class T> ax::NodeEditor::Details::SafePointerType<Tag>::SafePointerType(T*) [with T = T; Tag = ax::NodeEditor::NodeId]
     template <typename T = void> explicit SafePointerType(T* ptr): SafeType(reinterpret_cast<uintptr_t>(ptr)) {}
                                           ^~~~~~~~~~~~~~~
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h:67:28: note:   inherited here
     using SafePointerType::SafePointerType;
                            ^~~~~~~~~~~~~~~
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h:67:28: note:   template argument deduction/substitution failed:
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h:61:11: note:   mismatched types ‘T*’ and ‘int’
 const Tag SafePointerType<Tag>::Invalid{0};
           ^~~~~~~~~~~~~~~~~~~~
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h:45:8: note: candidate: constexpr ax::NodeEditor::Details::SafePointerType<ax::NodeEditor::NodeId>::SafePointerType(const ax::NodeEditor::Details::SafePointerType<ax::NodeEditor::NodeId>&)
 struct SafePointerType: SafeType<uintptr_t, Tag>
        ^~~~~~~~~~~~~~~
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h:67:28: note:   inherited here
     using SafePointerType::SafePointerType;
                            ^~~~~~~~~~~~~~~
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h:67:28: note:   an inherited constructor is not a candidate for initialization from an expression of the same or derived type
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h:45:8: note: candidate: constexpr ax::NodeEditor::Details::SafePointerType<ax::NodeEditor::NodeId>::SafePointerType(ax::NodeEditor::Details::SafePointerType<ax::NodeEditor::NodeId>&&)
 struct SafePointerType: SafeType<uintptr_t, Tag>
        ^~~~~~~~~~~~~~~
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h:67:28: note:   inherited here
     using SafePointerType::SafePointerType;
                            ^~~~~~~~~~~~~~~
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h:67:28: note:   an inherited constructor is not a candidate for initialization from an expression of the same or derived type
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h:65:8: note: candidate: ax::NodeEditor::NodeId::NodeId()
 struct NodeId final: Details::SafePointerType<NodeId>
        ^~~~~~
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h:65:8: note:   candidate expects 0 arguments, 1 provided
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h:65:8: note: candidate: constexpr ax::NodeEditor::NodeId::NodeId(const ax::NodeEditor::NodeId&)
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h:65:8: note:   no known conversion for argument 1 from ‘int’ to ‘const ax::NodeEditor::NodeId&’
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h:65:8: note: candidate: constexpr ax::NodeEditor::NodeId::NodeId(ax::NodeEditor::NodeId&&)
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h:65:8: note:   no known conversion for argument 1 from ‘int’ to ‘ax::NodeEditor::NodeId&&’
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h: In instantiation of ‘const ax::NodeEditor::LinkId ax::NodeEditor::Details::SafePointerType<ax::NodeEditor::LinkId>::Invalid’:
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Source/Editor.h:86:28:   required from here
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h:61:11: error: no matching function for call to ‘ax::NodeEditor::LinkId::LinkId(<brace-enclosed initializer list>)’
 const Tag SafePointerType<Tag>::Invalid{0};
           ^~~~~~~~~~~~~~~~~~~~
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h:51:43: note: candidate: template<class T> ax::NodeEditor::Details::SafePointerType<Tag>::SafePointerType(T*) [with T = T; Tag = ax::NodeEditor::LinkId]
     template <typename T = void> explicit SafePointerType(T* ptr): SafeType(reinterpret_cast<uintptr_t>(ptr)) {}
                                           ^~~~~~~~~~~~~~~
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h:72:28: note:   inherited here
     using SafePointerType::SafePointerType;
                            ^~~~~~~~~~~~~~~
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h:72:28: note:   template argument deduction/substitution failed:
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h:61:11: note:   mismatched types ‘T*’ and ‘int’
 const Tag SafePointerType<Tag>::Invalid{0};
           ^~~~~~~~~~~~~~~~~~~~
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h:45:8: note: candidate: constexpr ax::NodeEditor::Details::SafePointerType<ax::NodeEditor::LinkId>::SafePointerType(const ax::NodeEditor::Details::SafePointerType<ax::NodeEditor::LinkId>&)
 struct SafePointerType: SafeType<uintptr_t, Tag>
        ^~~~~~~~~~~~~~~
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h:72:28: note:   inherited here
     using SafePointerType::SafePointerType;
                            ^~~~~~~~~~~~~~~
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h:72:28: note:   an inherited constructor is not a candidate for initialization from an expression of the same or derived type
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h:45:8: note: candidate: constexpr ax::NodeEditor::Details::SafePointerType<ax::NodeEditor::LinkId>::SafePointerType(ax::NodeEditor::Details::SafePointerType<ax::NodeEditor::LinkId>&&)
 struct SafePointerType: SafeType<uintptr_t, Tag>
        ^~~~~~~~~~~~~~~
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h:72:28: note:   inherited here
     using SafePointerType::SafePointerType;
                            ^~~~~~~~~~~~~~~
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h:72:28: note:   an inherited constructor is not a candidate for initialization from an expression of the same or derived type
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h:70:8: note: candidate: ax::NodeEditor::LinkId::LinkId()
 struct LinkId final: Details::SafePointerType<LinkId>
        ^~~~~~
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h:70:8: note:   candidate expects 0 arguments, 1 provided
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h:70:8: note: candidate: constexpr ax::NodeEditor::LinkId::LinkId(const ax::NodeEditor::LinkId&)
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h:70:8: note:   no known conversion for argument 1 from ‘int’ to ‘const ax::NodeEditor::LinkId&’
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h:70:8: note: candidate: constexpr ax::NodeEditor::LinkId::LinkId(ax::NodeEditor::LinkId&&)
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h:70:8: note:   no known conversion for argument 1 from ‘int’ to ‘ax::NodeEditor::LinkId&&’
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h: In instantiation of ‘const ax::NodeEditor::PinId ax::NodeEditor::Details::SafePointerType<ax::NodeEditor::PinId>::Invalid’:
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Source/Editor.h:94:27:   required from here
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h:61:11: error: no matching function for call to ‘ax::NodeEditor::PinId::PinId(<brace-enclosed initializer list>)’
 const Tag SafePointerType<Tag>::Invalid{0};
           ^~~~~~~~~~~~~~~~~~~~
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h:51:43: note: candidate: template<class T> ax::NodeEditor::Details::SafePointerType<Tag>::SafePointerType(T*) [with T = T; Tag = ax::NodeEditor::PinId]
     template <typename T = void> explicit SafePointerType(T* ptr): SafeType(reinterpret_cast<uintptr_t>(ptr)) {}
                                           ^~~~~~~~~~~~~~~
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h:77:28: note:   inherited here
     using SafePointerType::SafePointerType;
                            ^~~~~~~~~~~~~~~
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h:77:28: note:   template argument deduction/substitution failed:
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h:61:11: note:   mismatched types ‘T*’ and ‘int’
 const Tag SafePointerType<Tag>::Invalid{0};
           ^~~~~~~~~~~~~~~~~~~~
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h:45:8: note: candidate: constexpr ax::NodeEditor::Details::SafePointerType<ax::NodeEditor::PinId>::SafePointerType(const ax::NodeEditor::Details::SafePointerType<ax::NodeEditor::PinId>&)
 struct SafePointerType: SafeType<uintptr_t, Tag>
        ^~~~~~~~~~~~~~~
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h:77:28: note:   inherited here
     using SafePointerType::SafePointerType;
                            ^~~~~~~~~~~~~~~
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h:77:28: note:   an inherited constructor is not a candidate for initialization from an expression of the same or derived type
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h:45:8: note: candidate: constexpr ax::NodeEditor::Details::SafePointerType<ax::NodeEditor::PinId>::SafePointerType(ax::NodeEditor::Details::SafePointerType<ax::NodeEditor::PinId>&&)
 struct SafePointerType: SafeType<uintptr_t, Tag>
        ^~~~~~~~~~~~~~~
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h:77:28: note:   inherited here
     using SafePointerType::SafePointerType;
                            ^~~~~~~~~~~~~~~
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h:77:28: note:   an inherited constructor is not a candidate for initialization from an expression of the same or derived type
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h:75:8: note: candidate: ax::NodeEditor::PinId::PinId()
 struct PinId final: Details::SafePointerType<PinId>
        ^~~~~
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h:75:8: note:   candidate expects 0 arguments, 1 provided
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h:75:8: note: candidate: constexpr ax::NodeEditor::PinId::PinId(const ax::NodeEditor::PinId&)
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h:75:8: note:   no known conversion for argument 1 from ‘int’ to ‘const ax::NodeEditor::PinId&’
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h:75:8: note: candidate: constexpr ax::NodeEditor::PinId::PinId(ax::NodeEditor::PinId&&)
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h:75:8: note:   no known conversion for argument 1 from ‘int’ to ‘ax::NodeEditor::PinId&&’
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h: In instantiation of ‘ax::NodeEditor::Details::SafePointerType<Tag>::SafePointerType(T*) [with T = void; Tag = ax::NodeEditor::NodeId]’:
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h:67:28:   required from ‘int BuildIdList(C&, I*, int, F&&) [with C = const std::vector<ax::NodeEditor::Detail::Object*>; I = ax::NodeEditor::NodeId; F = ax::NodeEditor::GetSelectedNodes(ax::NodeEditor::NodeId*, int)::<lambda(auto:1)>]’
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Source/NodeEditor.cpp:427:6:   required from here
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h:51:109: error: no matching function for call to ‘ax::NodeEditor::Details::SafeType<long unsigned int, ax::NodeEditor::NodeId>::SafeType()’
     template <typename T = void> explicit SafePointerType(T* ptr): SafeType(reinterpret_cast<uintptr_t>(ptr)) {}
                                                                                                             ^
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h:33:5: note: candidate: template<class T2, class Tag2> ax::NodeEditor::Details::SafeType<T, Tag>::SafeType(const ax::NodeEditor::Details::SafeType<T2, Tag2>&) <deleted>
     SafeType(const SafeType<T2, Tag2>&) = delete;
     ^~~~~~~~
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h:33:5: note:   template argument deduction/substitution failed:
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h:51:109: note:   candidate expects 1 argument, 0 provided
     template <typename T = void> explicit SafePointerType(T* ptr): SafeType(reinterpret_cast<uintptr_t>(ptr)) {}
                                                                                                             ^
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h:31:5: note: candidate: constexpr ax::NodeEditor::Details::SafeType<T, Tag>::SafeType(const ax::NodeEditor::Details::SafeType<T, Tag>&) [with T = long unsigned int; Tag = ax::NodeEditor::NodeId]
     SafeType(const SafeType&) = default;
     ^~~~~~~~
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h:31:5: note:   candidate expects 1 argument, 0 provided
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h:30:5: note: candidate: ax::NodeEditor::Details::SafeType<T, Tag>::SafeType(T) [with T = long unsigned int; Tag = ax::NodeEditor::NodeId]
     SafeType(T t): m_Value(std::move(t)) {}
     ^~~~~~~~
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h:30:5: note:   candidate expects 1 argument, 0 provided
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h: In instantiation of ‘ax::NodeEditor::Details::SafePointerType<Tag>::SafePointerType(T*) [with T = void; Tag = ax::NodeEditor::LinkId]’:
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h:72:28:   required from ‘int BuildIdList(C&, I*, int, F&&) [with C = const std::vector<ax::NodeEditor::Detail::Object*>; I = ax::NodeEditor::LinkId; F = ax::NodeEditor::GetSelectedLinks(ax::NodeEditor::LinkId*, int)::<lambda(auto:2)>]’
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Source/NodeEditor.cpp:435:6:   required from here
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h:51:109: error: no matching function for call to ‘ax::NodeEditor::Details::SafeType<long unsigned int, ax::NodeEditor::LinkId>::SafeType()’
     template <typename T = void> explicit SafePointerType(T* ptr): SafeType(reinterpret_cast<uintptr_t>(ptr)) {}
                                                                                                             ^
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h:33:5: note: candidate: template<class T2, class Tag2> ax::NodeEditor::Details::SafeType<T, Tag>::SafeType(const ax::NodeEditor::Details::SafeType<T2, Tag2>&) <deleted>
     SafeType(const SafeType<T2, Tag2>&) = delete;
     ^~~~~~~~
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h:33:5: note:   template argument deduction/substitution failed:
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h:51:109: note:   candidate expects 1 argument, 0 provided
     template <typename T = void> explicit SafePointerType(T* ptr): SafeType(reinterpret_cast<uintptr_t>(ptr)) {}
                                                                                                             ^
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h:31:5: note: candidate: constexpr ax::NodeEditor::Details::SafeType<T, Tag>::SafeType(const ax::NodeEditor::Details::SafeType<T, Tag>&) [with T = long unsigned int; Tag = ax::NodeEditor::LinkId]
     SafeType(const SafeType&) = default;
     ^~~~~~~~
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h:31:5: note:   candidate expects 1 argument, 0 provided
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h:30:5: note: candidate: ax::NodeEditor::Details::SafeType<T, Tag>::SafeType(T) [with T = long unsigned int; Tag = ax::NodeEditor::LinkId]
     SafeType(T t): m_Value(std::move(t)) {}
     ^~~~~~~~
/home/malik/workspace/opensource/imgui-node-editor/NodeEditor/Include/NodeEditor.h:30:5: note:   candidate expects 1 argument, 0 provided
NodeEditor/CMakeFiles/NodeEditor.dir/build.make:62: recipe for target 'NodeEditor/CMakeFiles/NodeEditor.dir/Source/NodeEditor.cpp.o' failed
make[2]: *** [NodeEditor/CMakeFiles/NodeEditor.dir/Source/NodeEditor.cpp.o] Error 1
CMakeFiles/Makefile2:176: recipe for target 'NodeEditor/CMakeFiles/NodeEditor.dir/all' failed
make[1]: *** [NodeEditor/CMakeFiles/NodeEditor.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by thedmd** [comment]
Can you try latest version? `using SafeType::SafeType;` was replaced to fix compilation on clang. Should also help with GCC.

**Comment by thedmd** [comment]
Now code should build fine.
